name: Tests

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set env
      run: |
        python3 -m venv env
    - name: Install dependencies
      run: |
        . env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Test with pytest
      run: |
        . env/bin/activate
        pip install pytest
        py.test tests

  build36:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6 venv
      run: |
        sudo apt-get install python3-venv
    - name: Set env
      run: |
        python3 -m venv env
    - name: Install dependencies
      run: |
        . env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Test with pytest
      run: |
        . env/bin/activate
        pip install pytest
        py.test tests
