name: Tests

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set env & dependencies
      env:
        CHIA_MACHINE_SSH_KEY: ${{ secrets.CHIA_MACHINE_SSH_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        . setup.sh
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${CHIA_MACHINE_SSH_KEY}"
    - name: Test with pytest
      run: |
        pip install pytest
        py.test tests
